import "./ResultCard.css";

/**
 * Displays a prediction result shaped like:
 * {
 *   prediction: "Cancer" | "Non-Cancer" | "Uncertain",
 *   type: string,
 *   confidence: number,
 *   is_uncertain?: boolean,
 *   gradcam_image?: string,
 * }
 */
export default function ResultCard({ result }) {
  if (!result) return null;

  if (result.is_uncertain) {
    return (
      <div className="result-card result-card--uncertain">
        <div className="result-card__header">
          <span className="result-card__status-dot" aria-hidden="true" />
          <h3 className="result-card__prediction">Not a Clear Skin Lesion Photo</h3>
        </div>

        <p className="result-card__uncertain-text">{result.type}</p>

        <p className="result-card__uncertain-note">
          The model's top confidence was only {result.confidence.toFixed(1)}% — too low to
          give a reliable classification. This usually means the photo isn't a close-up
          dermoscopic image of a lesion (e.g. it's a regular photo of skin, or an unrelated
          image). Try uploading a clearer, closer photo of the specific lesion.
        </p>

        <p className="result-card__disclaimer">
          This is a heuristic check, not a guaranteed filter — the model can occasionally
          still be confidently wrong on images unlike its training data.
        </p>
      </div>
    );
  }

  const isCancer = result.prediction === "Cancer";

  return (
    <div className={`result-card ${isCancer ? "result-card--alert" : "result-card--ok"}`}>
      <div className="result-card__header">
        <span className="result-card__status-dot" aria-hidden="true" />
        <h3 className="result-card__prediction">
          {isCancer ? "Potentially Cancerous" : "Likely Non-Cancerous"}
        </h3>
      </div>

      <div className="result-card__grid">
        <div className="result-card__field">
          <span className="result-card__label">Prediction</span>
          <span className="result-card__value">{result.prediction}</span>
        </div>

        <div className="result-card__field">
          <span className="result-card__label">Predicted Type</span>
          <span className="result-card__value">{result.type}</span>
        </div>

        <div className="result-card__field result-card__field--wide">
          <span className="result-card__label">Confidence</span>
          <div className="result-card__confidence">
            <div className="result-card__bar">
              <div
                className="result-card__bar-fill"
                style={{ width: `${result.confidence}%` }}
              />
            </div>
            <span className="result-card__confidence-value">
              {result.confidence.toFixed(1)}%
            </span>
          </div>
        </div>
      </div>

      {result.gradcam_image && (
        <div className="result-card__gradcam">
          <span className="result-card__label">Where the model looked (Grad-CAM)</span>
          <img
            src={result.gradcam_image}
            alt="Grad-CAM heatmap showing which region of the image influenced the prediction"
            className="result-card__gradcam-img"
          />
        </div>
      )}

      <p className="result-card__disclaimer">
        This result is generated by an AI research prototype and is intended to support,
        not replace, evaluation by a qualified dermatologist. Please consult a medical
        professional for an official diagnosis.
      </p>
    </div>
  );
}
