import "./ResultCard.css";

/**
 * Displays a prediction result shaped like:
 * { prediction: "Cancer" | "Non-Cancer", type: string, confidence: number }
 */
export default function ResultCard({ result }) {
  if (!result) return null;

  const isCancer = result.prediction === "Cancer";

  return (
    <div className={`result-card ${isCancer ? "result-card--alert" : "result-card--ok"}`}>
      <div className="result-card__header">
        <span className="result-card__status-dot" aria-hidden="true" />
        <h3 className="result-card__prediction">
          {isCancer ? "Potentially Cancerous" : "Likely Non-Cancerous"}
        </h3>
      </div>

      <div className="result-card__grid">
        <div className="result-card__field">
          <span className="result-card__label">Prediction</span>
          <span className="result-card__value">{result.prediction}</span>
        </div>

        <div className="result-card__field">
          <span className="result-card__label">Predicted Type</span>
          <span className="result-card__value">{result.type}</span>
        </div>

        <div className="result-card__field result-card__field--wide">
          <span className="result-card__label">Confidence</span>
          <div className="result-card__confidence">
            <div className="result-card__bar">
              <div
                className="result-card__bar-fill"
                style={{ width: `${result.confidence}%` }}
              />
            </div>
            <span className="result-card__confidence-value">
              {result.confidence.toFixed(1)}%
            </span>
          </div>
        </div>
      </div>

      <p className="result-card__disclaimer">
        This result is generated by an AI research prototype and is intended to support,
        not replace, evaluation by a qualified dermatologist. Please consult a medical
        professional for an official diagnosis.
      </p>
    </div>
  );
}
